# -*- coding: utf-8 -*-
"""Lab_Ass_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ny2_fhcIsUK0HkmmwhptAD_V01cUZhhD

Simulation and Modeling Lab  
**Course Code:** CSE 413  
Lab Task 1

# Necessary Libraries
"""

import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import random
from matplotlib.lines import lineStyles

"""# Scaler and Built In Functions"""

# ===============================
# Student's Assignment 1: Basic Matrix Operations
# ===============================


# 1. Create two 3×3 matrices with random integers
Matrix_A = np.random.randint(1, 100, (3, 3))
Matrix_B = np.random.randint(1, 100, (3, 3))

# 2. Perform addition, subtraction, and multiplication

matrix_add = Matrix_A + Matrix_B
matrix_sub = Matrix_A - Matrix_B
matrix_multi = Matrix_A @ Matrix_B   # Matrix multiplication

# 3. Compute determinant, inverse, and rank

# Determinants
det_A = np.linalg.det(Matrix_A)
det_B = np.linalg.det(Matrix_B)

# Inverse (safe floating-point check)
if not np.isclose(det_A, 0):
    inv_A = np.linalg.inv(Matrix_A)
else:
    inv_A = "[ERROR] Matrix A is singular, cannot compute inverse."

if not np.isclose(det_B, 0):
    inv_B = np.linalg.inv(Matrix_B)
else:
    inv_B = "[ERROR] Matrix B is singular, cannot compute inverse."

# Rank
rank_A = np.linalg.matrix_rank(Matrix_A)
rank_B = np.linalg.matrix_rank(Matrix_B)

# Print Results
print("Matrix A:\n", Matrix_A)
print("\nMatrix B:\n", Matrix_B)

print("\nMatrix Addition:\n", matrix_add)
print("\nMatrix Subtraction:\n", matrix_sub)
print("\nMatrix Multiplication:\n", matrix_multi)

print("\nDeterminant of Matrix A:\n", det_A)
print("Determinant of Matrix B:\n", det_B)

print("\nInverse of Matrix A:\n", inv_A)
print("\nInverse of Matrix B:\n", inv_B)

print("\nRank of Matrix A:", rank_A)
print("Rank of Matrix B:", rank_B)


# ===============================
# Student's Assignment 2: Matrix Plotting and Visualization
# ===============================

# a. Create two vectors, each containing 15 random floats
vector_A = np.random.uniform(0, 16, 15)
vector_B = np.random.uniform(30, 46, 15)

x = np.arange(len(vector_A))

# b. Plot the vectors
plt.figure(figsize=(8, 5))
plt.plot(x, vector_A, marker='o', linestyle='-', label="Vector A")
plt.plot(x, vector_B, marker='s', linestyle='-', label="Vector B")

# c. Labels and title
plt.xlabel("Index")
plt.ylabel("Values")
plt.title("Comparison of Two Random Vectors")
plt.legend()
plt.grid(True)

# Print vectors
print("\nVector A:\n", vector_A)
print("\nVector B:\n", vector_B)

plt.show()